
"""
Below sets the method names that will be generated by has_state_decorator
If you don't want a specific method below, just set its value to None
"""

METHOD_NAME_SAVE_STATE = "save_state"
METHOD_NAME_GET_STATE = "get_state"
METHOD_NAME_DEL_STATE = "del_state"
METHOD_NAME_FROM_POINTER = "from"
METHOD_NAME_GET_ID = "get_id"
